name: Deploy to Cloudflare

on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke Cloudflare Webhook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.CLOUDFLARE_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
